package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'GnWorkLoadInquiryVcs'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("GnWorkLoadInquiryVcs")) {
    val expected = GitVcsRoot({
        id("GnWorkLoadInquiryVcs")
        name = "https://github.com/lxxsgy//GN.WorkLoad.Inquiry.git#refs/heads/master"
        url = "https://github.com/lxxsgy//GN.WorkLoad.Inquiry.git"
        branch = "refs/heads/master"
        authMethod = password {
            userName = "lxxsgy"
            password = "sgylxx520"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        name = "https://github.com/lxxsgy/GN.WorkLoad.Inquiry.git#refs/heads/master"
        url = "https://github.com/lxxsgy/GN.WorkLoad.Inquiry.git"
        authMethod = password {
            userName = "lxxsgy"
            password = "credentialsJSON:f47a1892-d19f-4134-bfef-0c8c796290c0"
        }
    }

}
